### ISSUE TITLE
Release GMT 6.5.0

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#8017]
**Version**:  6.5

**Scheduled date**: Jan, 5, 2024

**Before release**:

- [x] check if all tests pass on macOS, Linux and Windows
- [x] check if other GMT-derived projects work well
	- [x] MB-System (@PaulWessel)
	- [x] GMTSAR (@PaulWessel)
	- [x] GMT.jl (@joa-quim)
	- [x] PyGMT (@leouieda, @seisman, @weiji14, @maxrjones)
	- [x] gmtmex (@PaulWessel, @joa-quim)
- [x] reserve a DOI on [zenodo](https://zenodo.org) (@PaulWessel)
- [x] run `src/gmt_make_*.sh` to update some .c and .h files
- [x] run `admin/gs_check.sh` to test if latest ghostscript version works
- [x] update [changelog](https://github.com/GenericMappingTools/gmt/blob/master/doc/rst/source/changes.rst)
- [x] update the version information in CITATION.cff
- [x] check installation instructions in [install.rst](https://github.com/GenericMappingTools/gmt/tree/master/doc/rst/source/install.rst)
- [x] check if there are any warnings when building the documentation
- [x] add one new entry in `doc/rst/_static/version_switch.js` if it's a minor release
- [x] check/set values in `cmake/ConfigDefault.cmake`
    - [x] `GMT_VERSION_YEAR` is current year
    - [x] `GMT_PACKAGE_VERSION_*` is correctly set
    - [x] `GMT_LIB_SOVERSION` is correctly set
    - [x] set `GMT_PUBLIC_RELEASE` to `TRUE`
    - [x] update `GMT_VERSION_DOI`
- [x] freeze codes and commit all changes to GitHub

**Release**:

- [x] create source tarballs (tar.gz and tar.xz) (@PaulWessel)
- [x] create macOS bundle (@PaulWessel)
- [x] create Windows win64 installer (@joa-quim)
- [x] create Windows win64 portable (@joa-quim?)
- [x] check if the source tarballs for Linux work well (@Esteban82, @anbj)
- [x] check if the macOS bundles work well (@seisman, @maxrjones)
- [x] check if the Windows installers work well (volunteers needed!)
- [x] upload source tarballs, macOS bundle, Windows installers to the GMT FTP (@PaulWessel)
- [x] update README and VERSION files on the GMT FTP (@PaulWessel)
- [x] make a tag and push it to github (**Must be done after uploading packages to the GMT FTP**)
    ```bash
    # checkout master (for minor releases) or 6.x branch (for patch releases)
    git checkout XXXX
    # create the tag 6.5
    git tag6.5
    # Push tags to GitHub
    git push --tags
    ```
- [x] make a GitHub release.
  The GitHub Actions automatically create a draft release after pushing the tag to github.
  We need to go to the [GitHub Release](https://github.com/GenericMappingTools/gmt/releases) page, and review it manually.
  - [x] 7 files are attached as release assets (2 source tarballs, 4 installers and 1 checksum file).
  - [x] download the checksum file and check if the checksums are correct
  - [x] edit the draft release, set the target to the correct tag, and publish the release
- [x] upload the tarball to zenodo (@PaulWessel)
- [x] make announcements in the [GMT forum](https://forum.generic-mapping-tools.org/)
- [ ] make announcements on the [GMT twitter](https://twitter.com/gmt_dev)
- [x] make announcements on the [GMT Instagram](https://www.instagram.com/genericmappingtools/)
- [x] update links on the main site (Download & Documentation) https://github.com/GenericMappingTools/website/pull/150
- [ ] update install instructions on the wiki if needed

**After release**:

- [x] create branch 6.x for bug-fixes if this is a minor release (i.e. create branch 6.1 after 6.1.0 is released)
  ```
  git checkout master
  git checkout -b 6.5
  git push --set-upstream origin 6.5
  ```
- [x] update `GMT_PACKAGE_VERSION_*` in `cmake/ConfigDefault.cmake` #8263
- [x] comment the `set (GMT_PUBLIC_RELEASE TRUE)` line #8263
- [x] commit changes to GitHub #8263

**3rd-party update**

**Volunteers needed!** Please let us know if you volunteer to help to maintain GMT in these 3rd-party tools.

- [x] update [conda-forge feedstock](https://github.com/conda-forge/gmt-feedstock) (@leouieda, @seisman, @weiji14) https://github.com/conda-forge/gmt-feedstock/pull/282
- [x] update [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gmt.rb) (@claudiodsf, @seisman) https://github.com/Homebrew/homebrew-core/commit/e95a7cae0fa53cc2662784afec79b2bce1ae36fc
- [x] update [macports ports](https://github.com/macports/macports-ports/blob/master/science/gmt5/Portfile) (@remkos, @seisman) https://github.com/macports/macports-ports/pull/22084
- [x] update [the RPM repository](https://copr.fedorainfracloud.org/coprs/genericmappingtools/gmt/) (@seisman)
- [x] update the [try-gmt](https://github.com/GenericMappingTools/try-gmt) Jupyter lab (@weiji14, @seisman, @maxrjones)
- [x] update [winget manifest file](https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/GenericMappingTools/gmt) (@seisman) https://github.com/microsoft/winget-pkgs/pull/133249

---

- [ ] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by Esteban82** [comment]
When we update/release the new datasets?

**Comment by PaulWessel** [comment]
Yes, we should be able to release the datasets the same day.

**Comment by PaulWessel** [comment]
We should probably add a tickbox for "Updating all new remove data to main oceania server".

**Comment by PaulWessel** [comment]
I suggest we aim for 6.5 release on Dec 1, otherwise we'll not get there in 2023.  I know there are outstanding issues with bugs but there always are.  No way to fix everything unfortunately. We can always to a 6.5.1 if there are good reasons after fixing some bugs.
@maxrjones, might you be able to help with the ChangeLog again?

**Comment by maxrjones** [comment]
>  @maxrjones, might you be able to help with the ChangeLog again?

Yes, no problem. do you anticipate any noteworthy changes between now and Dec 1?

**Comment by PaulWessel** [comment]
Want to update the gsfml repo but [trouble](https://github.com/PaulWessel/gsfml/issues/8).  Wonder is one of our CMake experts can help?

**Comment by PaulWessel** [comment]
> > @maxrjones, might you be able to help with the ChangeLog again?
> 
> Yes, no problem. do you anticipate any noteworthy changes between now and Dec 1?

Sorry the delay... Since Dec 1 is tomorrow I think so. Maybe wait to do anything until I post again here.

**Comment by joa-quim** [comment]
I don't think the AGU argument makes much sense anymore (and people only update GMT if the want/know-how). I would rather get it out before 8 December.

**Comment by PaulWessel** [comment]
It is true that now we have close to 1200 tests while in the olden day we would make code changes, have no tests, and then gott bitten by various issues, often on different platforms. Of course, nobody is forced to update software a few days before AGU.  I know many who wait weeks and months and even years to update their macOS version, so it is always buyer be aware (caveat emptor).

**Comment by joa-quim** [comment]
We could start building it today no?

**Comment by PaulWessel** [comment]
Hi @maxrjones, no more new things will be added to GMT after both @joa-quim (grdvs30 and grdshake added to seis supplement) and I (added gsfml supplement) have done our thing.  Safe to do ChangeLog now.

**Comment by maxrjones** [comment]
> Hi @maxrjones, no more new things will be added to GMT after both @joa-quim (grdvs30 and grdshake added to seis supplement) and I (added gsfml supplement) have done our thing. Safe to do ChangeLog now.

Sounds good, I'll be able to do this later today. BTW I no longer have an intel mac.

**Comment by remkos** [comment]
I do.

**Comment by maxrjones** [comment]
@PaulWessel I am assuming we're not going to include all the longoptions updates in the changelog and will just have announce them all once complete - is this correct?

**Comment by PaulWessel** [comment]
No, no word about long-options until GMT 7 probably.

**Comment by PaulWessel** [comment]
BTW, after much yelling and cursing I finally got mac port to install GDAL... SO looks like I can build the installers but I will ask several people to try so they know what to do.

**Comment by PaulWessel** [comment]
Oddest thing yesterday. Built the macOS bundle on M1 Silicon and when I tried to used it it immediately crashed! Rebooted, updated MacPorts with any changes there the last few days, and voila, worked again. Also got my macnut in Hawaii updated to the latest macOS Monterey the old gnome (2014) can handle,
Xcode etc and now can build the Intel bundle as well.  I suggest we simply pick Friday Dec 15th. As of today:

1. Freeze on anything new.
2. OK to fix warnings and simple bugs that gets discovered the next days.  Please run tests if you do.
3. Let us help each other to complete the Changeling (change.rst).
4. Hopefully @federico is back by then and he and I can (for the first time) test the "duplicate the candidate server to the oceania server".  I am thinking of first duplicating Oceania on the unused test server in case we learn some nasty lessons.  But candidate works well so don't expect trouble.
5. This time-line gives us basically the weekend to announce on website, Instagram and X. Or did we decide in Oslo that X is shit and we should get off?

If I have forgotten something critical here (not listed in checklist) please ping asap.  Yes, there are many more bugs listed in the issues but it is not possible to fix everything in a finite short time.  There is always 6.5.1 if something stupid shows up.

**Comment by PaulWessel** [comment]
I just clicked "freeze the code" since we are drawing a line in the sand today. Only allowed to fix typos in docs and add to changes.rst.

**Comment by PaulWessel** [comment]
Nice to see 100% of tests pass again.

**Comment by Esteban82** [comment]
> 4\. Hopefully @federico is back by then and he and I can (for the first time) test the "duplicate the candidate server to the oceania server".  I am thinking of first duplicating Oceania on the unused test server in case we learn some nasty lessons.  But candidate works well so don't expect troubl

I am back. How should I try this?

**Comment by PaulWessel** [comment]
Do git pull on gmtadmin-server for a few tiny updates tonight. You should able to test-run the eventual update of oceania.  If you do make test-release the script will build a script, copy it to the server /tmp, and run it.  This will place everything from candidate to test server.  You may wipe the test server first via make test-delete. If you want to be very cautious then comment the last lime in the scripts/test-release.sh file so it does not actually run the script it copies to teh server.  Examine the script it makes manually to see if it looks reasonable - ask me if you have questions or see any monkey-business.

At some point you can probably undo that comment and start from scratch and run make test-release again.  Then you can do export GMT_DATA_SERVER=test in a terminal and then try to make some new plots.  Make sure it creates the right directories in ~/.gmt/test/...

OK?

**Comment by PaulWessel** [comment]
Sorry, just added some fixes I forgot to commit.

**Comment by Esteban82** [comment]
I am testing it. It seems that it is working fine. But I am getting some errors because of this dir (`/export/gmtserver/gmt/test/server/earth/earth_relief2.5`).  @PaulWessel could you delete it please.

**Comment by Esteban82** [comment]
PaulWessel the `test server` is working fine.  I test it with remote_map_check.sh (of the remote-dataset repository) including earth_mdt and I got all the maps.

**Comment by PaulWessel** [comment]
Wonderful! Thanks Federico, we are ready for the server release once we get 6.5 released first. A few days maybe.

**Comment by PaulWessel** [comment]
Struggling with my ancient Mac Pro Intel [2014] again.  When running the full build I get this odd message:

ninja: error: loading 'build.ninja': No such file or directory

The CmakeError.log says

ld: Library not found for -lSystem

Also finding errors related to "missing" include files io.h and direct.h which are Windows files. WTF? As it is I am unable to build the x64 bundle.  Anyone else who can?

**Comment by PaulWessel** [comment]
I have placed the two tar versions and the arm64 for Mac installer in my pub/releases directory:

faac08659811eaa2e5336e654d62ba0d3ecd2168ac9f7157f3da5a69bba7ddae  gmt-6.5.0-darwin-arm64.dmg
e7af80ec3e5735fd9536b53b2b920b9f96a435b59d63421f61e21fe2a11960a2  gmt-6.5.0-src.tar.gz
75198c690d2babf54cea8adb47697b0dcf23af219da3dac52eda9812c3a75478  gmt-6.5.0-src.tar.xz

in ftp.soest.hawaii.edu:/export/ftp1/ftp/pub/pwessel/release.  Hopefully, @Esteban82 and @anbj can test those on Linux and maybe @seisman and @maxrjones can check the M1 bundle?

**Comment by PaulWessel** [comment]
@maxrjones, might you be able to look at the ChangeLog again since pre-AGU and make any updates to changes.rst?  Down the road it may be useful to have your recipe/steps in writing in case others have to step in and do that task.

**Comment by Esteban82** [comment]
Paul, is this the URL? https://ftp.soest.hawaii.edu/pwessel/release/
What is that string? is the checksum?

**Comment by PaulWessel** [comment]
You'll have to experiment I think since ftp is tricker than it used to be.  Play with the extra directory pub as well.  Yes the strings are the checksums (sha256 hash) as it says in the build-release.sh file.

**Comment by anbj** [comment]
Built and Tested **gmt-6.5.0-src.tar.gz**.
Looks good.

**Comment by seisman** [comment]
Should we merge #8038 first?

**Comment by joa-quim** [comment]
See #8254

**Comment by joa-quim** [comment]
Win installer and portable

https://fct-gmt.ualg.pt/tmp/GMT5/gmt-6.5.0-win64.exe
https://fct-gmt.ualg.pt/tmp/GMT5/gmt-6.5.0-win64.zip

**Comment by PaulWessel** [comment]
Great, I have placed them in the SOEST ftp release with the others.  Might you add the sha256 tags here?

**Comment by joa-quim** [comment]
Edited.

**Comment by anbj** [comment]
Tested a couple of commands on the portable versions, and looks very good.

**Comment by maxrjones** [comment]
> @maxrjones, might you be able to look at the ChangeLog again since pre-AGU and make any updates to changes.rst? Down the road it may be useful to have your recipe/steps in writing in case others have to step in and do that task.

Looking now - very sorry for dropping the ball on this!

**Comment by PaulWessel** [comment]
I have rebuilt the two tar source balls and the macOS arm64 installer.  Here are the latest sha256 hashes:

4d6f02987311d37a9311c13d47a8ffac6fb5f1e4dfb09628c2be39fdba7c883b  gmt-6.5.0-darwin-arm64.dmg
07f3e743b3a6dc2dfb7a22f79cbfe48f5b0196562a432bd27bdb5762036ea417  gmt-6.5.0-src.tar.gz
a2a40c64982bbded1671a1ace915d6433ff1a246c9ee6e41a715256b5f3fc062  gmt-6.5.0-src.tar.xz

**Comment by PaulWessel** [comment]
I am unable to build macOS x86-64 installer on my Mac Pro sitting in Hawaii as the signing fails.  Is there anyone who have an Intel mac that can help build the installer, i.e., cd to top gmt dir and run admin/build-release.sh with MacPorts?

**Comment by remkos** [comment]
> I am unable to build macOS x86-64 installer on my Mac Pro sitting in Hawaii as the signing fails. Is there anyone who have an Intel mac that can help build the installer, i.e., cd to top gmt dir and run admin/build-release.sh with MacPorts?

I've done my best. Does this work for you?

https://www.dropbox.com/scl/fi/s0epcssvkvhbeon75i34y/gmt-6.5.0-darwin-x86_64.dmg?rlkey=wohrwhaagh1op85z0wf1wugzq&dl=0

**Comment by remkos** [comment]
Sorry, that one is not proper, as I still have not been able to get the example images from `dvc`

**Comment by PaulWessel** [comment]
OK. I take it you have installed dvc but have you gotten authorised (?) via @maxrjones  to interact with DVC.  I guess it should not be necessary to pull from DVC. So what is the trouble if you are at the top dir (which contains subdirectories cmake, src, etc) and `run dvc pull`?

**Comment by maxrjones** [comment]
A couple options:
1. Remko and I could setup a zoom or async work on debugging the dvc issues
2. We could remove https://github.com/GenericMappingTools/gmt/blob/af1a38b864b53dcd12aca296b97ed3608b9ef63d/admin/ConfigReleaseBuild.cmake#L27-L34 since I do not think Paul or I have the ability to codesign the bundle anymore. This would allow @PaulWessel to build from the Hawaii Mac Pro.

**Comment by PaulWessel** [comment]
Yes, that works.  Instead of removing (because the signing worked on my M1) I will add another option, e.g., -s, that is needed to do signing.  Thanks @maxrjones for reminding me where that happened.

**Comment by PaulWessel** [comment]
Remind me, your UH account is maxjones or mjones?

**Comment by PaulWessel** [comment]
`admin/bulid-release` [-s] now works.  I signed it on arm64 and not on X68_64.

**Comment by PaulWessel** [comment]
@seisman, I think we are good to release 6.5. no?  I would feel better if you handled the release stuff (git, GitHub, and set tag etc) as I tend to foul that up..
Once released I can do the release of new oceania data (or @Esteban82 could if he is able to).

**Comment by seisman** [comment]
OK. I'll let you know when I finishes the git release.

**Comment by seisman** [comment]
@PaulWessel Could you please upload the tarballs and installers to the GMT FTP first?

**Comment by PaulWessel** [comment]
SUre, forgot.  I put them on my pub release page but will do this now.

**Comment by PaulWessel** [comment]
Done, I hope, even with correct permission I think.

**Comment by seisman** [comment]
The file permissions are incorrect.

**Comment by seisman** [comment]
> Win installer and portable
> 
> https://fct-gmt.ualg.pt/tmp/GMT5/gmt-6.5.0-win64.exe 0B4D47058E0B00F20A467DBA260AAB6238B705E8C6C6FA5B0D7FB237410532E2
> 
> https://fct-gmt.ualg.pt/tmp/GMT5/gmt-6.5.0-win64.zip DE7E05F87896FFB87E73F24EFB2FE21BE608CDED02AE0C3569652866E1448658

Quick question: we no longer provide the win32 installer?

**Comment by PaulWessel** [comment]
No, those are deprecated I think, per @joa-quim .

**Comment by seisman** [comment]
> > Win installer and portable
> > https://fct-gmt.ualg.pt/tmp/GMT5/gmt-6.5.0-win64.exe 0B4D47058E0B00F20A467DBA260AAB6238B705E8C6C6FA5B0D7FB237410532E2
> > https://fct-gmt.ualg.pt/tmp/GMT5/gmt-6.5.0-win64.zip DE7E05F87896FFB87E73F24EFB2FE21BE608CDED02AE0C3569652866E1448658
> 
> Quick question: we no longer provide the win32 installer?

OK, we dropped the win32 support in https://github.com/GenericMappingTools/gmt/issues/6857.

**Comment by seisman** [comment]
@PaulWessel The file permissions on the FTP are still incorrect.

**Comment by PaulWessel** [comment]
You mean the binary files. Yes. just added r t to group and other.

**Comment by seisman** [comment]
The win64 installer is likely incorrect.



> Win installer and portable
> 
> https://fct-gmt.ualg.pt/tmp/GMT5/gmt-6.5.0-win64.exe 0B4D47058E0B00F20A467DBA260AAB6238B705E8C6C6FA5B0D7FB237410532E2
> 
> https://fct-gmt.ualg.pt/tmp/GMT5/gmt-6.5.0-win64.zip DE7E05F87896FFB87E73F24EFB2FE21BE608CDED02AE0C3569652866E1448658

This is the sha256sum from @joa-quim, but the one on the GMT FTP has:
```
e2253092cea91ce72adf994fdbbb51b2703b3406c2feb36410e79f9e0aac8990  gmt-6.5.0-win64.exe
```

**Comment by PaulWessel** [comment]
Not sure how that happened but use @joa-quim's numbers (and even file if in doubt).

**Comment by seisman** [comment]
I've made the 6.5.0 release at https://github.com/GenericMappingTools/gmt/releases/tag/6.5.0, using @joa-quim's files and sha256sums in https://github.com/GenericMappingTools/gmt/issues/8017#issuecomment-1874444352.

Apprarently, @joa-quim edited the sha256sum numbers yesterday:
<img width="960" alt="image" src="https://github.com/GenericMappingTools/gmt/assets/3974108/45be2036-d761-4153-9da1-42e4669f74be">

`e2253092cea91ce72adf994fdbbb51b2703b3406c2feb36410e79f9e0aac8990` is the old sha256sum number. It means the one on the GMT FTP is the old one.

@PaulWessel Please download the latest win64 installers (both the exe and the zip) and upload them to the FTP server again.

**Comment by PaulWessel** [comment]
The two Win binary files have been placed in the gmt ftp on SOEST ftp server and should have correct permissions.

**Comment by PaulWessel** [comment]
I guess next steps are

1. Approve and merge https://github.com/GenericMappingTools/remote-datasets/pull/113.
2. Update oceania server with files from candidate (@PaulWessel or @Esteban82).
3. Website already updated with links to 6.5 so nothing to do there
4. Instagram post announcing 6.5 and massive addition of remote data set (@Esteban82  ?)
5. Twitter (X) post announcing the same things (@maxrjones ?)
6. ???

**Comment by seisman** [comment]
FYI, I've uploaded the tarball to Zenodo. The new record is at https://zenodo.org/records/10119499.

**Comment by PaulWessel** [comment]
I added a news item on the forum under Announcement. Feel free to edit if my links are off...

**Comment by Esteban82** [comment]
Paul, do you want me to do this? 

- Update oceania server with files from candidate

**Comment by PaulWessel** [comment]
Sure. Forst do a **git pull** as I have made two changes:

1. Renamed srv_server-release.sh to just server-release.sh (in scripts folder to match the other *-release names)
2. Remove the temporary echo statement that prevents the final command to execute (that ssh on the script in /tmp).

Since you did test-release.sh earlier and this is very similar except using server we should be good to go, and if anything goes wrong we have all the files we need still in candidate.  Please go ahead.

**Comment by PaulWessel** [comment]
So should just be

`make server-release`

which runs the right script.

**Comment by Esteban82** [comment]
@PaulWessel I am affraid I can't do it

```
-bash-4.2$ pwd
/tmp
-bash-4.2$ ls -la release.sh 
-rwx--x--x 1 pwessel gmt 602 ene  7 03:14 release.sh
-bash-4.2$ bash release.sh 
bash: release.sh: Permission denied
```

**Comment by PaulWessel** [comment]
Sorry, I need to delete that first.  Hold a few seconds.

**Comment by PaulWessel** [comment]
OK, gone , should work now.

**Comment by Esteban82** [comment]
Now I could run it. 

I am getting a lot of messagges like this:
I would say that for every directory.

```
rsync: failed to set times on "/export/gmtserver/gmt/data/server/.": Operation not permitted (1)
rsync: failed to set times on "/export/gmtserver/gmt/data/server/earth": Operation not permitted (1)
rsync: failed to set times on "/export/gmtserver/gmt/data/server/earth/earth_day": Operation not permitted (1)
```

**Comment by PaulWessel** [comment]
Yes, I think they are harmless.  This is what Ross told me I think: If I (or you) create some files then the other person cannot change permissions etc and get these types of messages.  Probably rsync info that gets messed up.

I expect the solution is to have a single user (e.g., gmtdata@soest.hawaii.edu) that we both use when doing server work.  In fact, it would be inserted into the various scripts.

I also need to but GeoScope about taking over the hosting of these data since at some point teh SOEST server will get old and die (and me too!) so then we need to have bus-factor protection for this part of GMT.  I will look into who I should contact.

Please check if you see anything funky regarding to permissions on oceania now, and if you can run plots from oceania and not set candidate server first.

**Comment by Esteban82** [comment]
It finished. This was the last message.

`rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1179) [sender=3.1.2]`

I test the oceania server and it is working fine.

**Comment by PaulWessel** [comment]
I am struggling a bit with making a USA map:

```
gmt grdimage @earth_relief_02m -B -RUS -png map
gmt [WARNING]: gmt_get_dataset_tiles: No earth_relief_02m_p tiles available for your region.
grdimage [ERROR]: Grid x range <= 0.0
grdimage [ERROR]: Make sure west < east for geographic coordinates
grdimage (gmt_api.c:2126(gmtapi_init_grdheader)): Please select compatible -R and -I values
grdimage [WARNING]: Your grid x's or longitudes appear to be outside the map region and will be skipped.
grdimage [WARNING]: No grid or image inside plot domain
```

but works fine for Argentina, for example.

**Comment by Esteban82** [comment]
> I am struggling a bit with making a USA map:
> 

I can't either. I could with 06m.

`gmt grdimage @earth_relief_06m -B -RUS -png map`

**Comment by Esteban82** [comment]
I just made the annoucement on instagram (https://www.instagram.com/p/C10k8Q9MN-m/). 

BTW, I think that we should announce also the new remote data sets available. I am thinking that I figure similar to this would be good. Could you do it @PaulWessel ?

https://www.instagram.com/p/CaFJFieLJ2y/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==

**Comment by Esteban82** [comment]
I check it on windows and looks fine.

**Comment by seisman** [comment]
> * make announcements on the [GMT twitter](https://twitter.com/gmt_dev)

Do we still want to do this? I think so, we have more than 1000 followers on Twitter.

**Comment by PaulWessel** [comment]
Any one care about Must and X? @leouieda, @maxrjones , or @Esteban82 ?

**Comment by maxrjones** [comment]
> Any one care about Must and X? @leouieda, @maxrjones , or @Esteban82 ?

I don't have interest in X

**Comment by Esteban82** [comment]
Me neither.

**Comment by seisman** [comment]
> OK, whoever wants to can remove the Twitter reminder from our checklist.

Done and pushed directly to the master branch.
